### ISSUE TITLE
Trees migration to maestro

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-project#403]
We need to migrate and document trees from Legacy system to Maestro.

I suggest to do it in following steps:
- Figure out contact person of tree
- Confirm contact is correct or update contact, request if they want to be migrated to Maestro system with following short questions:
- Record answers and submit to kernelci-project/maintainers/trees.yaml

Questions:
- Do you want to participate on early stages of development? E.g. participate in discussions on kernel options, tests we are enabling, reporting format, etc., so we keep you up to date with short summaries and you can provide feedback.
- What kind of reports do you want to receive? E.g. complete build report with links to logs on each checkout, short build summary, only automatically detected regressions, only human verified regressions(we have limited capacity on this and might miss some regressions), etc. Feel free to suggest your own format.
- What compilers + architectures + configuration do you want to be tested? Is default set OK for you?
- Do you want to test your tree on real hardware in labs? Do you have any tree specific tests you want to run and you can provide assistance with maintenance of this tests?

As follow up we need to create issue template for kernelci-project for new maintainers, with semi-automated submission of tree to configuration files.

List of trees to migrate:

- [x] agross https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git
- [x] amlogic https://git.kernel.org/pub/scm/linux/kernel/git/amlogic/linux.git
- [x] ardb https://git.kernel.org/pub/scm/linux/kernel/git/ardb/linux.git
- [x] arm64 https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git
- [x] arnd https://git.kernel.org/pub/scm/linux/kernel/git/arnd/playground.git
- [x] broonie-misc https://git.kernel.org/pub/scm/linux/kernel/git/broonie/misc.git
- [x] broonie-regmap https://git.kernel.org/pub/scm/linux/kernel/git/broonie/regmap.git
- [x] broonie-regulator https://git.kernel.org/pub/scm/linux/kernel/git/broonie/regulator.git
- [x] broonie-sound https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git
- [x] broonie-spi https://git.kernel.org/pub/scm/linux/kernel/git/broonie/spi.git
- [x] chrome-platform https://git.kernel.org/pub/scm/linux/kernel/git/chrome-platform/linux.git
- [x] clk https://git.kernel.org/pub/scm/linux/kernel/git/clk/linux.git
- [x] efi https://git.kernel.org/pub/scm/linux/kernel/git/efi/efi.git
- [x] khilman https://git.kernel.org/pub/scm/linux/kernel/git/khilman/linux.git
- [x] krzysztof https://git.kernel.org/pub/scm/linux/kernel/git/krzk/linux.git
- [x] kselftest https://git.kernel.org/pub/scm/linux/kernel/git/shuah/linux-kselftest.git
- [x] lee-backlight https://git.kernel.org/pub/scm/linux/kernel/git/lee/backlight.git
- [x] lee-mfd https://git.kernel.org/pub/scm/linux/kernel/git/lee/mfd.git
- [x] linusw https://git.kernel.org/pub/scm/linux/kernel/git/linusw/linux-gpio.git/
- [x] mainline https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
- [x] media https://git.linuxtv.org/media_tree.git
- [x] mediatek https://git.kernel.org/pub/scm/linux/kernel/git/mediatek/linux.git
- [x] net-next https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git
- [x] next https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git
- [x] omap https://git.kernel.org/pub/scm/linux/kernel/git/tmlind/linux-omap.git
- [x] peterz https://git.kernel.org/pub/scm/linux/kernel/git/peterz/queue.git
- [x] pm https://git.kernel.org/pub/scm/linux/kernel/git/rafael/linux-pm.git
- [x] renesas https://git.kernel.org/pub/scm/linux/kernel/git/geert/renesas-devel.git
- [x] riscv https://git.kernel.org/pub/scm/linux/kernel/git/riscv/linux.git
- [x] robh https://git.kernel.org/pub/scm/linux/kernel/git/robh/linux.git
- [x] rppt https://git.kernel.org/pub/scm/linux/kernel/git/rppt/memblock.git/
- [x] rt-stable https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git
- [x] #441
- [x] soc https://git.kernel.org/pub/scm/linux/kernel/git/soc/soc.git
- [x] tegra https://git.kernel.org/pub/scm/linux/kernel/git/tegra/linux.git
- [x] thermal https://git.kernel.org/pub/scm/linux/kernel/git/thermal/linux.git
- [x] tip https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git
- [x] ulfh https://git.kernel.org/pub/scm/linux/kernel/git/ulfh/mmc.git
- [x] vireshk https://git.kernel.org/pub/scm/linux/kernel/git/vireshk/linux.git

Outdated :

- [ ] alex https://git.linaro.org/people/alex.bennee/linux.git
- [ ] weiny2 https://github.com/weiny2/linux-kernel
- [ ] pmwg https://git.linaro.org/power/linux.git
- [ ] qcom-lt https://git.codelinaro.org/linaro/qcomlt/kernel
- [ ] evalenti https://git.kernel.org/pub/scm/linux/kernel/git/evalenti/linux-soc-thermal.git
- [ ] gtucker https://gitlab.collabora.com/gtucker/linux.git
- [ ] samsung https://git.kernel.org/pub/scm/linux/kernel/git/kgene/linux-samsung.git
- [ ] rmk git://git.armlinux.org.uk/~rmk/linux-arm.git

trees.yaml format is following:

```yaml
# Format of file is also documented at top of file in comments
# This file is used to store information about trees that are being tested by kernelci
# It is used to store information about the tree, the contact person, the mailing list, the build configurations, and the type of report that is desired
# Mail addresses are obfuscated to prevent spam with ROT13 (Rot13 / Caesar)
# build_configs is kernel configurations important for maintainer, special types are: default (default set of configurations kernelci builds)
#   arch/compiler/defconfig+fragments
#   For example: x86_64/gcc-12/x86_64_defconfig
# report_type is the type of report that is desired, with the following options:
#   full: full build report with links to logs on each checkout
#   short: short build summary
#   regressions: only automatically detected regressions
#   human: only human verified regressions(we have limited capacity on this and might miss some regressions)
treename:
  development_participation: true
  contact: obfuscated contact email
  contact_name: contact name
  maillist: obfuscated mailing list email
  build_configs:
    - arch/compiler/defconfig+fragments
    - x86_64/gcc-12/x86_64_defconfig
    - mips/gcc-12/malta_defconfig
  report_type: full
  report_emails:
    - obfuscated email1
    - optional obfuscated email2
    - ...
```
